name: xray-detection
channels:
  - pytorch
  - conda-forge
dependencies:
  - accelerate=1.5.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - albucore=0.0.19
  - albumentations=1.4.20
  - altair=5.5.0
  - annotated-types=0.7.0
  - anyio=4.8.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attrs=25.1.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.9.31
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.0
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - box2d-py=2.3.8
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cmake=3.31.5
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cookiecutter=2.6.0
  - cpuonly=2.0
  - cpython=3.10.16
  - cycler=0.12.1
  - datasets=2.19.1
  - dav1d=1.2.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - dm-tree=0.1.8
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - evaluate=0.4.3
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - ffmpeg=6.1.2
  - filelock=3.17.0
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gast=0.6.0
  - gdk-pixbuf=2.42.12
  - gdown=5.2.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - graphviz=12.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - hpack=4.1.0
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.30.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imath=3.1.12
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.17.2
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.3.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.0.13
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libasprintf=0.23.1
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.65.5
  - libhwloc=2.11.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.24
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-arm-cpu-plugin=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libparquet=18.0.0
  - libpng=1.6.47
  - libprotobuf=5.27.5
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libutf8proc=2.8.0
  - libuv=1.50.0
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxml2=2.13.5
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvm-openmp=20.1.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.1.1
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - multiprocess=0.70.17
  - munkres=1.1.4
  - narwhals=1.37.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbdime=3.2.1
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nltk=3.8.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - orc=2.0.2
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=25.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - propcache=0.3.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-opencv=4.10.0
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pyarrow-hotfix=0.7
  - pycparser=2.22
  - pycryptodome=3.22.0
  - pydot=1.4.2
  - pydub=0.25.1
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rhash=1.4.5
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.11.4
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - stringzilla=3.12.3
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - tf-keras=2.17.0
  - threadpoolctl=3.6.0
  - timm=1.0.15
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - typer-slim=0.15.3
  - typer-slim-standard=0.15.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - uc-micro-py=1.0.3
  - ultralytics=8.3.122
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - uvicorn-standard=0.34.2
  - uvloop=0.21.0
  - watchfiles=1.0.5
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - ffmpy==0.5.0
      - fsspec==2025.3.0
      - gradio==5.23.1
      - gradio-client==1.8.0
      - groovy==0.1.2
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - huggingface-hub==0.29.3
      - ipynbname==2024.1.0.0
      - keras==3.9.0
      - libclang==18.1.1
      - markdown==3.7
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - optree==0.14.0
      - orjson==3.10.16
      - protobuf==4.25.6
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - rich==13.9.4
      - ruff==0.11.2
      - safehttpx==0.1.6
      - scikeras==0.13.0
      - semantic-version==2.10.0
      - starlette==0.46.1
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - termcolor==2.5.0
      - tomlkit==0.13.2
      - torch==2.6.0
      - torchvision==0.21.0
      - typer==0.15.2
      - uvicorn==0.34.0
